package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"api-gateway/graph/model"
	"context"
	"fmt"
	authpb "ouroboros/proto/generated/auth"
	connpb "ouroboros/proto/generated/connection"
	feedpb "ouroboros/proto/generated/feed"
	notificationpb "ouroboros/proto/generated/notification"
	postpb "ouroboros/proto/generated/post"
	profilepb "ouroboros/proto/generated/profile"
)

// CreatePost is the resolver for the createPost mutation.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	res, err := r.PostClient.CreatePost(ctx, &postpb.CreatePostRequest{
		AuthorId: input.AuthorID,
		Content:  input.Content,
	})
	if err != nil {
		return nil, err
	}

	return &model.Post{
		ID:        res.Id,
		Content:   res.Content,
		CreatedAt: res.CreatedAt,
		AuthorID:  res.AuthorId,
	}, nil
}


// FollowUser is the resolver for the followUser mutation.
func (r *mutationResolver) FollowUser(ctx context.Context, followerID string, followeeID string) (bool, error) {
	res, err := r.ConnectionClient.FollowUser(ctx, &connpb.FollowUserRequest{
		FollowerId: followerID,
		FolloweeId: followeeID,
	})
	if err != nil {
		return false, err
	}

	return res.Success, nil
}

// UnfollowUser is the resolver for the unfollowUser field.
func (r *mutationResolver) UnfollowUser(ctx context.Context, followerID string, followeeID string) (bool, error) {
	res, err := r.ConnectionClient.UnfollowUser(ctx, &connpb.UnfollowUserRequest{
		FollowerId: followerID,
		FolloweeId: followeeID,
	})
	if err != nil {
		return false, fmt.Errorf("failed to unfollow user: %w", err)
	}

	return res.Success, nil
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, id string) (bool, error) {
	// NOTE: You will need a NotificationClient added to your Resolver struct
	res, err := r.NotificationClient.MarkAsRead(ctx, &notificationpb.MarkAsReadRequest{
		NotificationId: id,
	})
	if err != nil {
		return false, fmt.Errorf("failed to mark notification as read: %w", err)
	}

	return res.Success, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
		panic(fmt.Errorf("not implemented: Me - me"))

	// NOTE: You need to implement auth middleware to inject the user ID into the context
	// userID, ok := ctx.Value("userID").(string)
	// if !ok || userID == "" {
	// 	return nil, fmt.Errorf("unauthorized: user not found in context")
	// }

	// // Re-use your existing User resolver logic!
	// return r.User(ctx, userID)
}

// User is the resolver for the user query.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	// 1. Fetch Auth details
	authRes, err := r.AuthClient.GetUser(ctx, &authpb.GetUserRequest{Id: id})
	if err != nil {
		return nil, err
	}

	// 2. Fetch Profile details
	profRes, err := r.ProfileClient.GetProfile(ctx, &profilepb.GetProfileRequest{UserId: id})
	if err != nil {
		return nil, err
	}

	// 3. Merge into the GraphQL model
	return &model.User{
		ID:          authRes.Id,
		Email:       authRes.Email,
		Username:    authRes.Username,
		DisplayName: &profRes.DisplayName,
		AvatarURL:   &profRes.AvatarUrl,
		Bio:         &profRes.Bio,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, ids []string) ([]*model.User, error) {
	// Note: Iterating like this is an N+1 problem.
	// If your gRPC services support batch fetching (e.g., GetUsers), you should use that instead.
	var users []*model.User
	for _, id := range ids {
		user, err := r.User(ctx, id)
		if err != nil {
			// Decide if you want to fail the whole query or just skip/return null for this user
			continue
		}
		users = append(users, user)
	}
	return users, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {

	req := &postpb.GetPostRequest{
		Id: id,
	}

	res, err := r.PostClient.GetPost(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch post: %w", err)
	}

	return &model.Post{
		ID:      res.Id,
		Content:   res.Content,
		CreatedAt: res.CreatedAt,
		AuthorID:  res.AuthorId,
		Author:    &model.User{ID: res.AuthorId},
	}, nil
}

// PostsByIds is the resolver for the postsByIds field.
// func (r *queryResolver) PostsByIds(ctx context.Context, ids []string) ([]*model.Post, error) {
// 	// Assuming your postpb has a batch fetch endpoint
// 	res, err := r.PostClient.GetPostsByIds()(ctx, &postpb.GetPostsByIdsRequest{
// 		Ids: ids,
// 	})
// 	if err != nil {
// 		return nil, fmt.Errorf("failed to fetch posts: %w", err)
// 	}

// 	var posts []*model.Post
// 	for _, p := range res.Posts {
// 		posts = append(posts, &model.Post{
// 			ID:        p.Id,
// 			Content:   p.Content,
// 			CreatedAt: p.CreatedAt,
// 			AuthorID:  p.AuthorId,
// 			Author:    &model.User{ID: p.AuthorId},
// 		})
// 	}
// 	return posts, nil
// }
// Feed is the resolver for the feed query.
func (r *queryResolver) Feed(ctx context.Context, userID string, limit *int32, cursor *string) (*model.FeedResponse, error) {
	// Call Feed Service
	feedRes, err := r.FeedClient.GetFeed(ctx, &feedpb.GetFeedRequest{UserId: userID})
	if err != nil {
		return nil, err
	}

	var items []*model.FeedItem
	for _, item := range feedRes.Items {
		items = append(items, &model.FeedItem{
			PostID: item.PostId,
			Cursor: item.Cursor,
		})
	}

	return &model.FeedResponse{Items: items}, nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, userID string, limit *int32) ([]*model.Notification, error) {
	// NOTE: Requires a NotificationClient
	var reqLimit int32 = 20 // default limit
	if limit != nil {
		reqLimit = *limit
	}

	res, err := r.NotificationClient.GetNotifications(ctx, &notificationpb.GetNotificationsRequest{
		UserId: userID,
		Limit:  reqLimit,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch notifications: %w", err)
	}

	var notifications []*model.Notification
	for _, n := range res.Notifications {
		notifications = append(notifications, &model.Notification{
			ID:        n.Id,
			Read:    n.Read,
			CreatedAt: n.CreatedAt,
		})
	}
	return notifications, nil
}

// PostsByIds is the resolver for the postsByIds field.
func (r *queryResolver) PostsByIds(ctx context.Context, ids []string) ([]*model.Post, error) {
	panic(fmt.Errorf("not implemented: PostsByIds - postsByIds"))
}

func (r *subscriptionResolver) NotificationReceived(ctx context.Context, userID string) (<-chan *model.Notification, error) {
	panic(fmt.Errorf("not implemented: NotificationReceived - notificationReceived"))
}

func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	panic(fmt.Errorf("not implemented: CreateComment - createComment"))
}

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }


// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }
