package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"api-gateway/graph/model"
	"context"
	"fmt"
	pb "ouroboros/proto/generated/" // Adjust this to match your actual proto module path
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, ids []string) ([]*model.User, error) {
	// Call the gRPC User Service
	req := &pb.BatchRequest{Ids: ids}
	res, err := r.UserServiceClient.BatchGetTest1(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch users: %w", err)
	}

	// Map gRPC response to GraphQL models
	var users []*model.User
	for _, item := range res.Items {
		users = append(users, &model.User{
			ID:        item.Id,
			MockData1: item.MockData_1,
		})
	}
	return users, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, ids []string) ([]*model.Todo, error) {
	// Call the gRPC Todo Service
	req := &pb.BatchRequest{Ids: ids}
	res, err := r.TodoServiceClient.BatchGetTest2(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch todos: %w", err)
	}

	// Map gRPC response to GraphQL models
	var todos []*model.Todo
	for _, item := range res.Items {
		todos = append(todos, &model.Todo{
			ID:        item.Id,
			MockData2: item.MockData_2,
		})
	}
	return todos, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
