// services.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/services.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common request/response for batching
type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_proto_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_proto_rawDescGZIP(), []int{0}
}

func (x *BatchRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Test1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MockData_1    string                 `protobuf:"bytes,2,opt,name=mock_data_1,json=mockData1,proto3" json:"mock_data_1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test1) Reset() {
	*x = Test1{}
	mi := &file_proto_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test1) ProtoMessage() {}

func (x *Test1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test1.ProtoReflect.Descriptor instead.
func (*Test1) Descriptor() ([]byte, []int) {
	return file_proto_services_proto_rawDescGZIP(), []int{1}
}

func (x *Test1) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Test1) GetMockData_1() string {
	if x != nil {
		return x.MockData_1
	}
	return ""
}

type Test1BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Test1               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test1BatchResponse) Reset() {
	*x = Test1BatchResponse{}
	mi := &file_proto_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test1BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test1BatchResponse) ProtoMessage() {}

func (x *Test1BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test1BatchResponse.ProtoReflect.Descriptor instead.
func (*Test1BatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_proto_rawDescGZIP(), []int{2}
}

func (x *Test1BatchResponse) GetItems() []*Test1 {
	if x != nil {
		return x.Items
	}
	return nil
}

type Test2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MockData_2    string                 `protobuf:"bytes,2,opt,name=mock_data_2,json=mockData2,proto3" json:"mock_data_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test2) Reset() {
	*x = Test2{}
	mi := &file_proto_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test2) ProtoMessage() {}

func (x *Test2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test2.ProtoReflect.Descriptor instead.
func (*Test2) Descriptor() ([]byte, []int) {
	return file_proto_services_proto_rawDescGZIP(), []int{3}
}

func (x *Test2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Test2) GetMockData_2() string {
	if x != nil {
		return x.MockData_2
	}
	return ""
}

type Test2BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Test2               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test2BatchResponse) Reset() {
	*x = Test2BatchResponse{}
	mi := &file_proto_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test2BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test2BatchResponse) ProtoMessage() {}

func (x *Test2BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test2BatchResponse.ProtoReflect.Descriptor instead.
func (*Test2BatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_proto_rawDescGZIP(), []int{4}
}

func (x *Test2BatchResponse) GetItems() []*Test2 {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_services_proto protoreflect.FileDescriptor

const file_proto_services_proto_rawDesc = "" +
	"\n" +
	"\x14proto/services.proto\x12\bservices\" \n" +
	"\fBatchRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"7\n" +
	"\x05Test1\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\vmock_data_1\x18\x02 \x01(\tR\tmockData1\";\n" +
	"\x12Test1BatchResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.services.Test1R\x05items\"7\n" +
	"\x05Test2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\vmock_data_2\x18\x02 \x01(\tR\tmockData2\";\n" +
	"\x12Test2BatchResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.services.Test2R\x05items2Q\n" +
	"\bService1\x12E\n" +
	"\rBatchGetTest1\x12\x16.services.BatchRequest\x1a\x1c.services.Test1BatchResponse2Q\n" +
	"\bService2\x12E\n" +
	"\rBatchGetTest2\x12\x16.services.BatchRequest\x1a\x1c.services.Test2BatchResponseB\x1aZ\x18ouroboros/proto;servicesb\x06proto3"

var (
	file_proto_services_proto_rawDescOnce sync.Once
	file_proto_services_proto_rawDescData []byte
)

func file_proto_services_proto_rawDescGZIP() []byte {
	file_proto_services_proto_rawDescOnce.Do(func() {
		file_proto_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_proto_rawDesc), len(file_proto_services_proto_rawDesc)))
	})
	return file_proto_services_proto_rawDescData
}

var file_proto_services_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_services_proto_goTypes = []any{
	(*BatchRequest)(nil),       // 0: services.BatchRequest
	(*Test1)(nil),              // 1: services.Test1
	(*Test1BatchResponse)(nil), // 2: services.Test1BatchResponse
	(*Test2)(nil),              // 3: services.Test2
	(*Test2BatchResponse)(nil), // 4: services.Test2BatchResponse
}
var file_proto_services_proto_depIdxs = []int32{
	1, // 0: services.Test1BatchResponse.items:type_name -> services.Test1
	3, // 1: services.Test2BatchResponse.items:type_name -> services.Test2
	0, // 2: services.Service1.BatchGetTest1:input_type -> services.BatchRequest
	0, // 3: services.Service2.BatchGetTest2:input_type -> services.BatchRequest
	2, // 4: services.Service1.BatchGetTest1:output_type -> services.Test1BatchResponse
	4, // 5: services.Service2.BatchGetTest2:output_type -> services.Test2BatchResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_services_proto_init() }
func file_proto_services_proto_init() {
	if File_proto_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_proto_rawDesc), len(file_proto_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_services_proto_goTypes,
		DependencyIndexes: file_proto_services_proto_depIdxs,
		MessageInfos:      file_proto_services_proto_msgTypes,
	}.Build()
	File_proto_services_proto = out.File
	file_proto_services_proto_goTypes = nil
	file_proto_services_proto_depIdxs = nil
}
