// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Comment struct {
	ID        string `json:"id"`
	PostID    string `json:"postId"`
	AuthorID  string `json:"authorId"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
	Author    *User  `json:"author"`
}

type ConnectResponse struct {
	Success bool `json:"success"`
}

type CreateCommentInput struct {
	AuthorID string `json:"authorId"`
	PostID   string `json:"postId"`
	Content  string `json:"content"`
}

type CreatePostInput struct {
	AuthorID string `json:"authorId"`
	Content  string `json:"content"`
}

type Experience struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Company   string  `json:"company"`
	StartDate string  `json:"startDate"`
	EndDate   *string `json:"endDate,omitempty"`
}

type FeedItem struct {
	PostID string `json:"postId"`
	Cursor string `json:"cursor"`
	Post   *Post  `json:"post,omitempty"`
}

type FeedResponse struct {
	Items []*FeedItem `json:"items"`
}

type Mutation struct {
}

type Notification struct {
	ID        string  `json:"id"`
	UserID    string  `json:"userId"`
	Type      string  `json:"type"`
	ActorID   string  `json:"actorId"`
	EntityID  *string `json:"entityId,omitempty"`
	CreatedAt string  `json:"createdAt"`
	Read      bool    `json:"read"`
	Actor     *User   `json:"actor,omitempty"`
}

type Post struct {
	ID        string     `json:"id"`
	Content   string     `json:"content"`
	CreatedAt string     `json:"createdAt"`
	AuthorID  string     `json:"authorId"`
	Author    *User      `json:"author"`
	Comments  []*Comment `json:"comments"`
}

type Profile struct {
	ID          string        `json:"id"`
	Headline    *string       `json:"headline,omitempty"`
	About       *string       `json:"about,omitempty"`
	Experiences []*Experience `json:"experiences"`
}

type Query struct {
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignOutResponse struct {
	Success bool `json:"success"`
}

type SignUpInput struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	DisplayName string `json:"displayName"`
}

type Subscription struct {
}

type UpdateProfileInput struct {
	Headline *string `json:"headline,omitempty"`
	About    *string `json:"about,omitempty"`
}

type User struct {
	ID             string  `json:"id"`
	Email          string  `json:"email"`
	Username       string  `json:"username"`
	DisplayName    *string `json:"displayName,omitempty"`
	AvatarURL      *string `json:"avatarUrl,omitempty"`
	Bio            *string `json:"bio,omitempty"`
	FollowersCount int32   `json:"followersCount"`
	FollowingCount int32   `json:"followingCount"`
	IsFollowing    bool    `json:"isFollowing"`
	Posts          []*Post `json:"posts"`
}
