// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type Todo struct {
	ID        string `json:"id"`
	MockData2 string `json:"mockData2"`
}

type User struct {
	ID        string `json:"id"`
	MockData1 string `json:"mockData1"`
}
